import type { Metadata } from 'next'
import type { PropsWithChildren } from 'react'

import './globals.css'
import Navbar from './components/Navbar.res.mjs'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
